package consts

const (
	APP_CONFIG_FILENAME = "config.json"

	TABLEMANAGER_MAX_PLAYERS        = 1024
	TABLEMANAGER_MESSAGE_STACK_SIZE = TABLEMANAGER_MAX_PLAYERS * PLAYER_MESSAGE_STACK_SIZE

	TABLE_MAX_PLAYERS = 16

	PLAYER_PREFIX_ID          = "pid-"
	PLAYER_MESSAGE_STACK_SIZE = 64

	TABLE_INTERVAL_LOOP = 50 // milliseconds
	TABLE_PREFIX_ID     = "tid-"
)
