package consts

const (
	APP_CONFIG_FILENAME = "config.json"

	CARD_PREFIX_ID = "cid-"

	DECK_DEFAULT_CARD_SIZE = 52

	GAME_BLACKJACK_MAX_GROUPS        = 16
	GAME_BLACKJACK_MAX_PLAYERS_GROUP = 1
	GAME_BLACKJACK_MIN_PLAYERS_GROUP = 1
	GAME_BLACKJACK_WINNING_SCORE     = 21

	TABLEMANAGER_MAX_PLAYERS        = 1024
	TABLEMANAGER_MESSAGE_STACK_SIZE = TABLEMANAGER_MAX_PLAYERS * PLAYER_MESSAGE_STACK_SIZE

	TABLE_MAX_PLAYERS = 16

	PLAYER_PREFIX_ID          = "pid-"
	PLAYER_MESSAGE_STACK_SIZE = 64

	TABLE_INTERVAL_LOOP = 500 // milliseconds
	TABLE_PREFIX_ID     = "tid-"
)
